### ISSUE TITLE
Lab showing up as incomplete for students

### ISSUE THREAD

**Issue by seemajune** [learn-co-curriculum/HTML-Forms-and-iFrames#1]
Students are complaining that this lab does not seem to be marked as finished when they have in fact validated the code and fixed all of the errors.

**Comment by AnnJohn** [comment]
Hi @seemajun, could you report this as a bug instead of an issue? It looks like this is a problem that the Labs team will need to fix. Thanks!

**Comment by seemajune** [comment]
will do!

**Comment by AnnJohn** [comment]
thanks!!
