### ISSUE TITLE
Input elements not displaying properly

### ISSUE THREAD

**Issue by interestinall** [learn-co-curriculum/HTML-Forms-and-iFrames#14]
The actual display of the form elements described is not ideal. For example, a border around the text/password/tel inputs would make it more obvious that you can actually test them out. The submit button just says submit and doesn't look like a button. Radios are not displaying, nor are the checkboxes. Select works but is not obvious to the user imo. Hope this feedback helps!

Chrome Version 51.0.2704.63 (64-bit) btw.

**Comment by ktravers** [comment]
@pletcher similar to https://github.com/learn-co-curriculum/html-map-contact-form-code-along/issues/10, this is not a parser error. you'll notice the form elements do not render on github readme either. will need to add inline styling to fix

**Comment by pletcher** [comment]
Thanks, @ktravers!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
