### ISSUE TITLE
Grammar Errors

### ISSUE THREAD

**Issue by digitalh2o2** [learn-co-curriculum/HTML-Forms-and-iFrames#4]
Hello,

There are grammatical errors in the first couple of sentences of the 'Forms' paragraph:

_Forms are essential for gathering user information from site visitors. Text can **be**(missing) inserted, **slections** made and a record of their responses can be sent **remoetly** to a server whose backend can store the information._

The headers for the 'username', 'password', 'phone' are below the images giving the paragraphs above them different meaning. 

In the 'Username' paragraph(should be password) in the last sentence:

This is useful when private information is entered that we **don not want** others around the user to read.

**Comment by AnnJohn** [comment]
thanks @digitalh2o2 we'll go ahead and update. If you notice issues like this in the future, it would be great if you could actually make the edit, and then we'll review and pull those edits in. 

Thanks!
